### ISSUE TITLE
Email Verification Regex is not complete.

### ISSUE THREAD

**Issue by haloboy777** [infosanity-in/infosanity-BE#5]
It should also allow _
For example, Windows Live Hotmail only allows creation of email addresses using alphanumerics, dot (.), underscore (_) and hyphen (-). [SOURCE](https://en.wikipedia.org/wiki/E-mail_address#Local-part)

https://github.com/infosanity-in/infosanity-BE/blob/553f2fbe025011b7f42c4ca608494383c4f515df/utils/constants.js#L16

**Comment by sgurjeet** [comment]
It does allow those.

**Comment by haloboy777** [comment]
`let reg = '/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/i'

"gurjeet_babbar@gmail.com".search(reg)
> -1
`

**Comment by haloboy777** [comment]
```
let reg = '/^(([^<>()[]\.,;:\s@"]+(.[^<>()[]\.,;:\s@"]+)*)|(".+"))@(([[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}])|(([a-zA-Z-0-9]+.)+[a-zA-Z]{2,}))$/i'

"gurjeet_babbar@gmail.com".search(reg)
> -1
```

**Comment by sgurjeet** [comment]
Remove the quotes surrounding the regex. You converted it to a string.
Also try regex.test(email

**Comment by haloboy777** [comment]
```
let reg = /^(([^<>()[]\.,;:\s@"]+(.[^<>()[]\.,;:\s@"]+)*)|(".+"))@(([[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}])|(([a-zA-Z-0-9]+.)+[a-zA-Z]{2,}))$/

"gurjeet_babbar@gmail.com".search(reg)
> -1

reg.test("gurjeet_babbar@gmail.com")
> false

```

**Comment by sgurjeet** [comment]
ye vala regex kaha is different than the one you mentioned first.
try the one in utils/constants.js

**Comment by haloboy777** [comment]
wtf.. maine toh wahi copy kiya thaa..
my bad.
I'll close this.
